project:
  type: website
  output-dir: docs

website:
  title: "Kray's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/freestok
      - icon: twitter
        href: https://twitter.com/spatialKray
format:
  html:
    theme: cosmo
    css: styles.css



